<?php
echo "<html><head>";
echo '<meta charset="utf-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<title>HoosCleanin - Student Cleaning Service</title>';
echo '<meta name="description" content="">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<meta name="robots" content="all,follow">';
echo '<!-- Bootstrap CSS-->';
echo '<link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css">';
echo '<!-- Font Awesome CSS-->';
echo '<link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">';
echo '<!-- Google fonts - Roboto -->';
echo '<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100">';
echo '<!-- owl carousel-->';
echo '<link rel="stylesheet" href="vendor/owl.carousel/assets/owl.carousel.css">';
echo '<link rel="stylesheet" href="vendor/owl.carousel/assets/owl.theme.default.css">';
echo '<!-- theme stylesheet-->';
echo '<link rel="stylesheet" href="css/style.default.css" id="theme-stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet"><link id="new-stylesheet" rel="stylesheet">';
echo '<!-- Custom stylesheet - for your changes-->';
echo '<link rel="stylesheet" href="css/custom.css">';
echo '<!-- Favicon-->';
echo '<link rel="shortcut icon" href="favicon.png">';
echo '<!-- Tweaks for older IEs--><!--[if lt IE 9]>';
echo '<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>';
echo '<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->';
echo '<script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/common.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/util.js"></script><script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/7/stats.js"></script></head>';
echo '<body>';
echo '<!-- navbar-->';
echo '<header class="header mb-5">';
echo '<!--';
echo '*** TOPBAR ***';
echo '_________________________________________________________';
echo '-->';
echo '<div id="top">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class = "toptab">';
echo '<div class="col-lg-6 text-center text-lg-left">HoosCleanin</div>';
echo '</div>';
echo '<div class="col-lg-6 text-center text-lg-right" style="position:absolute; left:525px;">';
echo '<ul class="menu list-inline mb-0">';
echo '<li class="list-inline-item"><a href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>';
echo '<li class="list-inline-item"><a href="register.html">Sign Up</a></li>';
echo '<li class="list-inline-item"><a href="contact.html">Contact</a></li>';
echo '</ul>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '<div id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true" class="modal fade">';
echo '<div class="modal-dialog modal-sm">';
echo '<div class="modal-content">';
echo '<div class="modal-header">';
echo '<h5 class="modal-title">Customer login</h5>';
echo '<button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>';
echo '</div>';
echo '<div class="modal-body">';
echo '<form action="" method="post">';
echo '<div class="form-group">';
echo '<input id="email-modal" type="text" placeholder="email" class="form-control">';
echo '</div>';
echo '<div class="form-group">';
echo '<input id="password-modal" type="password" placeholder="password" class="form-control">';
echo '</div>';
echo '<p class="text-center">';
echo '<button class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>';
echo '</p>';
echo '</form>';
echo '<p class="text-center text-muted">Not registered yet?</p>';
echo '<p class="text-center text-muted"><a href="register.html"><strong>Register now</strong></a>! It is easy and done in 1&nbsp;minute and gives you access to special discounts and much more!</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- *** TOP BAR END ***-->';
echo '';
echo '';
echo '</div>';
echo '<nav class="navbar navbar-expand-lg">';
echo '<div class="container"><a href="index.html" class="navbar-brand home"><img src="img/logo.png" alt="Obaju logo" class="d-none d-md-inline-block"><img src="img/logo.png" alt="Obaju logo" class="d-inline-block d-md-none"><span class="sr-only">Obaju - go to homepage</span></a>';
echo '<div class="navbar-buttons">';
echo '<button type="button" data-toggle="collapse" data-target="#navigation" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle navigation</span><i class="fa fa-align-justify"></i></button>';
echo '<button type="button" data-toggle="collapse" data-target="#search" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></button><a href="" class="btn btn-outline-secondary navbar-toggler"><i class="fa fa-shopping-cart"></i></a>';
echo '</div>';
echo '<div id="navigation" class="collapse navbar-collapse">';
echo '<ul class="navbar-nav mr-auto">';
echo '<li class="nav-item"><a href="index.html" class="nav-link active">Home</a></li>';
echo '<li class="nav-item"><a href="text.html" class="nav-link active">About US</a>';
echo '';
echo '</li>';
echo '<li class="nav-item dropdown menu-large show"><a href="#" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link" aria-expanded="true">Find a Cleaner<b class="caret"></b></a>';
echo '';
echo '</li>';
echo '<li class="nav-item dropdown menu-large show"><a href="#" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link" aria-expanded="true">Finding a Cleaning Job<b class="caret"></b></a>';
echo '';
echo '</li>';
echo '</ul>';
echo '<div class="navbar-buttons d-flex justify-content-end">';
echo '<!-- /.nav-collapse-->';
echo '<div id="search-not-mobile" class="navbar-collapse collapse"></div><a data-toggle="collapse" href="#search" class="btn navbar-btn btn-primary d-none d-lg-inline-block"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></a>';
echo '<div id="basket-overview" class="navbar-collapse collapse d-none d-lg-block"><a href="" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i><span>0 items in cart</span></a></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '<div id="search" class="collapse">';
echo '<div class="container">';
echo '<form role="search" class="ml-auto">';
echo '<div class="input-group">';
echo '<input type="text" placeholder="Search" class="form-control">';
echo '<div class="input-group-append">';
echo '<button type="button" class="btn btn-primary"><i class="fa fa-search"></i></button>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<div id="all">';
echo '<div id="content">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-md-12">';
echo '<div id="main-slider" class="owl-carousel owl-theme owl-loaded owl-drag">';
echo '';
echo '';
echo '';
echo '';
echo '<div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-2784px, 0px, 0px); transition: all 0s ease 0s; width: 3712px;"><div class="owl-item" style="width: 928px;"><div class="item"><img src="img/frontpage1.jpg" alt="" class="img-fluid"></div></div><div class="owl-item" style="width: 928px;"><div class="item"><img src="img/frontpage2.jpg" alt="" class="img-fluid"></div></div><div class="owl-item" style="width: 928px;"><div class="item"><img src="img/frontpage3.jpg" alt="" class="img-fluid"></div></div><div class="owl-item active" style="width: 928px;"><div class="item"><img src="img/frontpage4.jpg" alt="" class="img-fluid"></div></div></div></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button></div><div class="owl-thumbs"></div></div>';
echo '<!-- /#main-slider-->';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!--';
echo '*** ADVANTAGES HOMEPAGE ***';
echo '_________________________________________________________';
echo '-->';
echo '';
echo '<!-- /#advantages-->';
echo '<!-- *** ADVANTAGES END ***-->';
echo '<!--';
echo '*** HOT PRODUCT SLIDESHOW ***';
echo '_________________________________________________________';
echo '-->';
echo '';
echo '<!--';
echo '*** GET INSPIRED ***';
echo '_________________________________________________________';
echo '-->';
echo '';
echo '<!-- *** GET INSPIRED END ***-->';
echo '<!--';
echo '*** BLOG HOMEPAGE ***';
echo '_________________________________________________________';
echo '-->';
echo '<div class="box text-center">';
echo '<div class="container">';
echo '<div class="col-md-12">';
echo '<h3 class="text-uppercase">Hoos Gonna Clean Your Room</h3>';
echo '<p class="lead mb-0">Many college students have limited to clean their messy houses and apartments. In order to replace inflexible and costly professional cleaning services, we created a medium for connecting people in the Charlottesville community to clean for one another. Our easy-to-use website allows both students and non-students to pay each other for cleaning jobs on an as-needed basis. Check out our About Us page to learn more!</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="col-md-12">';
echo '<div id="blog-homepage" class="row">';
echo '<div class="col-sm-6">';
echo '<div class="post">';
echo '<h4><a href="">Hoos Cleaning?</a></h4>';
echo '';
echo '<hr>';
echo '<p class="intro">Find one of your fellow students to clean your house/apartment for a reasonable price!</p>';
echo '<p class="read-more"><a href="" class="btn btn-primary">Continue</a></p>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-6">';
echo '<div class="post">';
echo '<h4><a href="">Hoos House?</a></h4>';
echo '';
echo '<hr>';
echo '<p class="intro">Find a students apartment/house to clean to make some cash on the side!</p>';
echo '<p class="read-more"><a href="" class="btn btn-primary">Continue</a></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- /#blog-homepage-->';
echo '</div>';
echo '</div>';
echo '<!-- /.container-->';
echo '<!-- *** BLOG HOMEPAGE END ***-->';
echo '</div>';
echo '</div>';
echo '<!--';
echo '*** FOOTER ***';
echo '_________________________________________________________';
echo '-->';
echo '';
echo '<!-- /#footer-->';
echo '<!-- *** FOOTER END ***-->';
echo '';
echo '';
echo '<!--';
echo '*** COPYRIGHT ***';
echo '_________________________________________________________';
echo '-->';
echo '<div id="copyright">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 mb-2 mb-lg-0">';
echo '<p class="text-center text-lg-left">©2018 HoosCleanin LLC</p>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<p class="text-center text-lg-right">Template design by <a href="https://bootstrapious.com/e-commerce-templates">Bootstrapious: E-commerce</a>';
echo '<!-- Not removing these links is part of the licence conditions of the template. Thanks for understanding :)-->';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- *** COPYRIGHT END ***-->';
echo '<!-- JavaScript files-->';
echo '<script src="vendor/jquery/jquery.min.js"></script>';
echo '<script src="vendor/popper.js/umd/popper.min.js"> </script>';
echo '<script src="vendor/bootstrap/js/bootstrap.min.js"></script>';
echo '<script src="vendor/jquery.cookie/jquery.cookie.js"> </script>';
echo '<script src="vendor/owl.carousel/owl.carousel.min.js"></script>';
echo '<script src="vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.js"></script>';
echo '<script src="https://maps.googleapis.com/maps/api/js"></script>';
echo '<script src="js/front.js"></script>';
echo '';
echo '</body></html>';
?>